services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMK\MkContentAi\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    DMK\MkContentAi\Backend\EventListener\CustomFileControlsEventListener:
        tags:
            - name: event.listener
              method: handleEvent
              event: TYPO3\CMS\Backend\Form\Event\CustomFileControlsEvent

    DMK\MkContentAi\Backend\EventListener\ModifyFilelistButtonBarEventListener:
        tags:
            - name: event.listener
              method: handleEvent
              event: TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent

    DMK\MkContentAi\Backend\EventListener\FileListActionsEventListener:
        public: true
        tags:
            - name: event.listener
              method: handleEvent
              event: TYPO3\CMS\Filelist\Event\ProcessFileListActionsEvent

    DMK\MkContentAi\Command\AltTextGenerateCommand:
        tags:
            -
                name: console.command
                command: 'mkcontentai:alt-text-generate'
                description: 'Generate alt texts in specific directory - example: "1:/mkcontentai/openai"'
                schedulable: true

    DMK\MkContentAi\Utility\PermissionsUtility:
        calls:
            - method: 'injectContext'
              arguments:
                  $context: '@TYPO3\CMS\Core\Context\Context'
        public: true

    DMK\MkContentAi\Service\SiteLanguageService:
        public: true

    DMK\MkContentAi\Http\Client\AltTextClient:
        public: true

    DMK\MkContentAi\Service\AiAltTextService:
        public: true

    DMK\MkContentAi\Controller\BaseController:
        arguments:
            $pageRenderer: '@TYPO3\CMS\Core\Page\PageRenderer'
        public: true

    DMK\MkContentAi\Http\Client\Action\AltTextAction:
        public: true

    DMK\MkContentAi\Http\Client\StabilityAiClient:
        calls:
            - method: 'injectStabilityAction'
              arguments:
                  $stabilityAiAction: '@DMK\MkContentAi\Http\Client\Action\StabilityAiAction'
        public: true

    DMK\MkContentAi\Http\Client\StableDiffusionClient:
        calls:
            - method: 'injectStableDiffusionAction'
              arguments:
                  $stableDiffusionAction: '@DMK\MkContentAi\Http\Client\Action\StableDiffusionAction'
        public: true
